<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for GenerateArg class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class GenerateArg implements GenerateArgInterface
{

    /**
     * @var int
     */
    private $number;

    /**
     * @var bool
     */
    private $async;
    
    /**
     * @inheritdoc
     *
     * @return int
     */
    public function getNumber(): int
    {
        return (int) $this->number;
    }
    
    /**
     * @inheritdoc
     *
     * @param int $value
     * @return void
     */
    public function setNumber(int $value): void
    {
        $this->number = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return bool
     */
    public function getAsync(): bool
    {
        return (bool) $this->async;
    }
    
    /**
     * @inheritdoc
     *
     * @param bool $value
     * @return void
     */
    public function setAsync(bool $value): void
    {
        $this->async = $value;
    }
}
