<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for GenerateArg interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface GenerateArgInterface
{
    /**
     * Autogenerated description for getNumber() interface method
     *
     * @return int
     */
    public function getNumber(): int;

    /**
     * Autogenerated description for setNumber() interface method
     *
     * @param int $value
     * @return void
     */
    public function setNumber(int $value): void;

    /**
     * Autogenerated description for getAsync() interface method
     *
     * @return bool
     */
    public function getAsync(): bool;

    /**
     * Autogenerated description for setAsync() interface method
     *
     * @param bool $value
     * @return void
     */
    public function setAsync(bool $value): void;
}
