apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage-grpc-client-deployment
  labels:
    app: mage-grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mage-grpc-client
  template:
    metadata:
      labels:
        app: mage-grpc-client
    spec:
      containers:
        - name: mage-grpc-client-container-kube
          image: ogorkunad/magento-grpc-test-client:0.0.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: debug
              containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: mage-grpc-client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: mage-grpc-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage-grpc-phpserver-db-deployment
  labels:
    app: mage-grpc-phpserver-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mage-grpc-phpserver-db
  template:
    metadata:
      labels:
        app: mage-grpc-phpserver-db
    spec:
      containers:
        - name: mage-grpc-phpserver-db-container-kube
          image: ogorkunad/magento-grpc-test-phpserver-db:0.0.1
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: mage-grpc-phpserver-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      name: tcp
      targetPort: 5432
  selector:
    app: mage-grpc-phpserver-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage-grpc-phpserver-deployment
  labels:
    app: mage-grpc-phpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mage-grpc-phpserver
  template:
    metadata:
      labels:
        app: mage-grpc-phpserver
    spec:
      containers:
        - name: mage-grpc-phpserver-container-kube
          image: ogorkunad/magento-grpc-test-phpserver:0.0.1
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 9000
            - name: ssh
              containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: mage-grpc-phpserver
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      protocol: TCP
      name: grpc
      targetPort: 9000
    - port: 22
      protocol: TCP
      name: ssh
      targetPort: 22223
  selector:
    app: mage-grpc-phpserver
