<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magegrpc.proto

namespace Magento\GrpcTestApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *DTOs
 *
 * Generated from protobuf message <code>magento.grpcTestApi.proto.GenerateArg</code>
 */
class GenerateArg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 number = 1;</code>
     */
    protected $number = 0;
    /**
     * Generated from protobuf field <code>bool async = 2;</code>
     */
    protected $async = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $number
     *     @type bool $async
     * }
     */
    public function __construct($data = null)
    {
        \Magento\GrpcTestApi\Metadata\Magegrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 number = 1;</code>
     * @return int
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Generated from protobuf field <code>int32 number = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool async = 2;</code>
     * @return bool
     */
    public function getAsync()
    {
        return $this->async;
    }

    /**
     * Generated from protobuf field <code>bool async = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAsync($var)
    {
        GPBUtil::checkBool($var);
        $this->async = $var;

        return $this;
    }
}
