<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magegrpc.proto

namespace Magento\GrpcTestApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.grpcTestApi.proto.Option</code>
 */
class Option extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>float price = 3;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>bool available = 5;</code>
     */
    protected $available = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $title
     *     @type float $price
     *     @type bool $available
     * }
     */
    public function __construct($data = null)
    {
        \Magento\GrpcTestApi\Metadata\Magegrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, true);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 3;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool available = 5;</code>
     * @return bool
     */
    public function getAvailable()
    {
        return $this->available;
    }

    /**
     * Generated from protobuf field <code>bool available = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setAvailable($var)
    {
        GPBUtil::checkBool($var);
        $this->available = $var;

        return $this;
    }
}
