<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magegrpc.proto

namespace Magento\GrpcTestApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.grpcTestApi.proto.Product</code>
 */
class Product extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string sku = 2;</code>
     */
    protected $sku = '';
    /**
     * Generated from protobuf field <code>float price = 3;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>string title = 4;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string description = 5;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string img_url = 6;</code>
     */
    protected $img_url = '';
    /**
     * Generated from protobuf field <code>bool available = 7;</code>
     */
    protected $available = false;
    /**
     * Generated from protobuf field <code>repeated .magento.grpcTestApi.proto.Option options = 8;</code>
     */
    private $options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $sku
     *     @type float $price
     *     @type string $title
     *     @type string $description
     *     @type string $img_url
     *     @type bool $available
     *     @type \Magento\GrpcTestApi\Proto\Option[]|\Google\Protobuf\Internal\RepeatedField $options
     * }
     */
    public function __construct($data = null)
    {
        \Magento\GrpcTestApi\Metadata\Magegrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sku = 2;</code>
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * Generated from protobuf field <code>string sku = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSku($var)
    {
        GPBUtil::checkString($var, true);
        $this->sku = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float price = 3;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>float price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 4;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, true);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string img_url = 6;</code>
     * @return string
     */
    public function getImgUrl()
    {
        return $this->img_url;
    }

    /**
     * Generated from protobuf field <code>string img_url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setImgUrl($var)
    {
        GPBUtil::checkString($var, true);
        $this->img_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool available = 7;</code>
     * @return bool
     */
    public function getAvailable()
    {
        return $this->available;
    }

    /**
     * Generated from protobuf field <code>bool available = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setAvailable($var)
    {
        GPBUtil::checkBool($var);
        $this->available = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.grpcTestApi.proto.Option options = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.grpcTestApi.proto.Option options = 8;</code>
     * @param \Magento\GrpcTestApi\Proto\Option[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\GrpcTestApi\Proto\Option::class);
        $this->options = $arr;

        return $this;
    }
}
