<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magegrpc.proto

namespace Magento\GrpcTestApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.grpcTestApi.proto.ReadResponse</code>
 */
class ReadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .magento.grpcTestApi.proto.Product items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Magento\GrpcTestApi\Proto\Product[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = null)
    {
        \Magento\GrpcTestApi\Metadata\Magegrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .magento.grpcTestApi.proto.Product items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.grpcTestApi.proto.Product items = 1;</code>
     * @param \Magento\GrpcTestApi\Proto\Product[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\GrpcTestApi\Proto\Product::class);
        $this->items = $arr;

        return $this;
    }
}
