<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magegrpc.proto

namespace Magento\GrpcTestApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * read specified N products, just for testing
 *
 * Generated from protobuf message <code>magento.grpcTestApi.proto.ReadRequest</code>
 */
class ReadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 n = 1;</code>
     */
    protected $n = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $n
     * }
     */
    public function __construct($data = null)
    {
        \Magento\GrpcTestApi\Metadata\Magegrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 n = 1;</code>
     * @return int
     */
    public function getN()
    {
        return $this->n;
    }

    /**
     * Generated from protobuf field <code>int32 n = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setN($var)
    {
        GPBUtil::checkInt32($var);
        $this->n = $var;

        return $this;
    }
}
