<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api\Data;

/**
 * Autogenerated description for ClearArg interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ClearArgInterface
{
}
