<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api\Data;

/**
 * Autogenerated description for Option interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface OptionInterface
{
    /**
     * Autogenerated description for getId() interface method
     *
     * @return string
     */
    public function getId(): string;

    /**
     * Autogenerated description for setId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setId(string $value): void;

    /**
     * Autogenerated description for getTitle() interface method
     *
     * @return string
     */
    public function getTitle(): string;

    /**
     * Autogenerated description for setTitle() interface method
     *
     * @param string $value
     * @return void
     */
    public function setTitle(string $value): void;

    /**
     * Autogenerated description for getPrice() interface method
     *
     * @return float
     */
    public function getPrice(): float;

    /**
     * Autogenerated description for setPrice() interface method
     *
     * @param float $value
     * @return void
     */
    public function setPrice(float $value): void;

    /**
     * Autogenerated description for getAvailable() interface method
     *
     * @return bool
     */
    public function getAvailable(): bool;

    /**
     * Autogenerated description for setAvailable() interface method
     *
     * @param bool $value
     * @return void
     */
    public function setAvailable(bool $value): void;
}
