<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api\Data;

/**
 * Autogenerated description for Product interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ProductInterface
{
    /**
     * Autogenerated description for getId() interface method
     *
     * @return string
     */
    public function getId(): string;

    /**
     * Autogenerated description for setId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setId(string $value): void;

    /**
     * Autogenerated description for getSku() interface method
     *
     * @return string
     */
    public function getSku(): string;

    /**
     * Autogenerated description for setSku() interface method
     *
     * @param string $value
     * @return void
     */
    public function setSku(string $value): void;

    /**
     * Autogenerated description for getPrice() interface method
     *
     * @return float
     */
    public function getPrice(): float;

    /**
     * Autogenerated description for setPrice() interface method
     *
     * @param float $value
     * @return void
     */
    public function setPrice(float $value): void;

    /**
     * Autogenerated description for getTitle() interface method
     *
     * @return string
     */
    public function getTitle(): string;

    /**
     * Autogenerated description for setTitle() interface method
     *
     * @param string $value
     * @return void
     */
    public function setTitle(string $value): void;

    /**
     * Autogenerated description for getDescription() interface method
     *
     * @return string
     */
    public function getDescription(): string;

    /**
     * Autogenerated description for setDescription() interface method
     *
     * @param string $value
     * @return void
     */
    public function setDescription(string $value): void;

    /**
     * Autogenerated description for getImgUrl() interface method
     *
     * @return string
     */
    public function getImgUrl(): string;

    /**
     * Autogenerated description for setImgUrl() interface method
     *
     * @param string $value
     * @return void
     */
    public function setImgUrl(string $value): void;

    /**
     * Autogenerated description for getAvailable() interface method
     *
     * @return bool
     */
    public function getAvailable(): bool;

    /**
     * Autogenerated description for setAvailable() interface method
     *
     * @param bool $value
     * @return void
     */
    public function setAvailable(bool $value): void;

    /**
     * Autogenerated description for getOptions() interface method
     *
     * @return \Magento\GrpcTestApi\Api\Data\OptionInterface[]
     */
    public function getOptions(): array;

    /**
     * Autogenerated description for setOptions() interface method
     *
     * @param \Magento\GrpcTestApi\Api\Data\OptionInterface[] $value
     * @return void
     */
    public function setOptions(array $value): void;
}
