<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api\Data;

/**
 * Autogenerated description for ReadResponse class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class ReadResponse implements ReadResponseInterface
{

    /**
     * @var array
     */
    private $items;
    
    /**
     * @inheritdoc
     *
     * @return \Magento\GrpcTestApi\Api\Data\ProductInterface[]
     */
    public function getItems(): array
    {
        return (array) $this->items;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\GrpcTestApi\Api\Data\ProductInterface[] $value
     * @return void
     */
    public function setItems(array $value): void
    {
        $this->items = $value;
    }
}
