<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api\Data;

/**
 * Autogenerated description for ReadRequest class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class ReadRequest implements ReadRequestInterface
{

    /**
     * @var int
     */
    private $n;
    
    /**
     * @inheritdoc
     *
     * @return int
     */
    public function getN(): int
    {
        return (int) $this->n;
    }
    
    /**
     * @inheritdoc
     *
     * @param int $value
     * @return void
     */
    public function setN(int $value): void
    {
        $this->n = $value;
    }
}
