<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for ReadResponse class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class ReadResponseArrayMapper
{
    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
    * Convert the DTO to the array with the data
    *
    * @param ReadResponse $dto
    * @return array
    */
    public function convertToArray(ReadResponse $dto)
    {
        $result = [];
        /** Convert complex Array field **/
        $fieldArray = [];
        foreach ($dto->getItems() as $fieldArrayDto) {
            $fieldArray[] = $this->objectManager->get(\Magento\GrpcTestApi\Api\Data\ProductArrayMapper::class)
                ->convertToArray($fieldArrayDto);
        }
        $result["items"] = $fieldArray;
        return $result;
    }
}
