<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api\Data;

/**
 * Autogenerated description for ReadRequest interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ReadRequestInterface
{
    /**
     * Autogenerated description for getN() interface method
     *
     * @return int
     */
    public function getN(): int;

    /**
     * Autogenerated description for setN() interface method
     *
     * @param int $value
     * @return void
     */
    public function setN(int $value): void;
}
