// Code generated by protoc-gen-go. DO NOT EDIT.
// source: magegrpc.proto

package magegrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//DTOs
type GenerateArg struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Async                bool     `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateArg) Reset()         { *m = GenerateArg{} }
func (m *GenerateArg) String() string { return proto.CompactTextString(m) }
func (*GenerateArg) ProtoMessage()    {}
func (*GenerateArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8236dd47f2f81f, []int{0}
}

func (m *GenerateArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateArg.Unmarshal(m, b)
}
func (m *GenerateArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateArg.Marshal(b, m, deterministic)
}
func (m *GenerateArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateArg.Merge(m, src)
}
func (m *GenerateArg) XXX_Size() int {
	return xxx_messageInfo_GenerateArg.Size(m)
}
func (m *GenerateArg) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateArg.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateArg proto.InternalMessageInfo

func (m *GenerateArg) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *GenerateArg) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

type Option struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8236dd47f2f81f, []int{1}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Option) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Option) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Option) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type Product struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku                  string    `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Price                float32   `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Title                string    `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description          string    `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImgUrl               string    `protobuf:"bytes,6,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	Available            bool      `protobuf:"varint,7,opt,name=available,proto3" json:"available,omitempty"`
	Options              []*Option `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8236dd47f2f81f, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *Product) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Product) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type ClearArg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearArg) Reset()         { *m = ClearArg{} }
func (m *ClearArg) String() string { return proto.CompactTextString(m) }
func (*ClearArg) ProtoMessage()    {}
func (*ClearArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8236dd47f2f81f, []int{3}
}

func (m *ClearArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearArg.Unmarshal(m, b)
}
func (m *ClearArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearArg.Marshal(b, m, deterministic)
}
func (m *ClearArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearArg.Merge(m, src)
}
func (m *ClearArg) XXX_Size() int {
	return xxx_messageInfo_ClearArg.Size(m)
}
func (m *ClearArg) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearArg.DiscardUnknown(m)
}

var xxx_messageInfo_ClearArg proto.InternalMessageInfo

type Cleared struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cleared) Reset()         { *m = Cleared{} }
func (m *Cleared) String() string { return proto.CompactTextString(m) }
func (*Cleared) ProtoMessage()    {}
func (*Cleared) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8236dd47f2f81f, []int{4}
}

func (m *Cleared) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cleared.Unmarshal(m, b)
}
func (m *Cleared) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cleared.Marshal(b, m, deterministic)
}
func (m *Cleared) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cleared.Merge(m, src)
}
func (m *Cleared) XXX_Size() int {
	return xxx_messageInfo_Cleared.Size(m)
}
func (m *Cleared) XXX_DiscardUnknown() {
	xxx_messageInfo_Cleared.DiscardUnknown(m)
}

var xxx_messageInfo_Cleared proto.InternalMessageInfo

// read specified N products, just for testing
type ReadRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8236dd47f2f81f, []int{5}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type ReadResponse struct {
	Items                []*Product `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c8236dd47f2f81f, []int{6}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetItems() []*Product {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*GenerateArg)(nil), "magegrpc.GenerateArg")
	proto.RegisterType((*Option)(nil), "magegrpc.Option")
	proto.RegisterType((*Product)(nil), "magegrpc.Product")
	proto.RegisterType((*ClearArg)(nil), "magegrpc.ClearArg")
	proto.RegisterType((*Cleared)(nil), "magegrpc.Cleared")
	proto.RegisterType((*ReadRequest)(nil), "magegrpc.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "magegrpc.ReadResponse")
}

func init() { proto.RegisterFile("magegrpc.proto", fileDescriptor_7c8236dd47f2f81f) }

var fileDescriptor_7c8236dd47f2f81f = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x95, 0x77, 0x9b, 0xaf, 0xd9, 0xaa, 0x2a, 0x16, 0x14, 0x6b, 0xe1, 0x10, 0xe5, 0xc2, 0x8a,
	0x43, 0x84, 0x8a, 0x80, 0x03, 0xa7, 0xc2, 0x81, 0x23, 0xc8, 0x12, 0x67, 0xe4, 0x8d, 0x87, 0xc8,
	0x22, 0xb1, 0x83, 0xed, 0x20, 0xf1, 0x93, 0xf8, 0x4f, 0xfc, 0x18, 0x14, 0xc7, 0xdb, 0x84, 0x56,
	0xbd, 0xf9, 0xbd, 0xf9, 0x78, 0x6f, 0xc6, 0x03, 0x17, 0xbd, 0x68, 0xb1, 0xb5, 0x43, 0x53, 0x0f,
	0xd6, 0x78, 0x43, 0xf3, 0x13, 0xae, 0xde, 0xc3, 0xee, 0x13, 0x6a, 0xb4, 0xc2, 0xe3, 0x8d, 0x6d,
	0xe9, 0x15, 0xa4, 0x7a, 0xec, 0x8f, 0x68, 0x19, 0x29, 0xc9, 0x21, 0xe1, 0x11, 0xd1, 0xc7, 0x90,
	0x08, 0xf7, 0x5b, 0x37, 0x6c, 0x53, 0x92, 0x43, 0xce, 0x67, 0x50, 0x1d, 0x21, 0xfd, 0x3c, 0x78,
	0x65, 0x34, 0xbd, 0x80, 0x8d, 0x92, 0xa1, 0xa6, 0xe0, 0x1b, 0x25, 0xa7, 0x7c, 0xaf, 0x7c, 0x87,
	0x21, 0xbf, 0xe0, 0x33, 0x98, 0xd8, 0xc1, 0xaa, 0x06, 0xd9, 0xb6, 0x24, 0x87, 0x0d, 0x9f, 0x01,
	0x7d, 0x0e, 0x85, 0xf8, 0x25, 0x54, 0x27, 0x8e, 0x1d, 0xb2, 0x24, 0xf4, 0x5f, 0x88, 0xea, 0x2f,
	0x81, 0xec, 0x8b, 0x35, 0x72, 0x6c, 0xfc, 0x3d, 0x95, 0x4b, 0xd8, 0xba, 0x1f, 0x63, 0xd4, 0x98,
	0x9e, 0x0f, 0x28, 0xdc, 0xba, 0x39, 0x5b, 0xbb, 0x29, 0x61, 0x27, 0xd1, 0x35, 0x56, 0x85, 0x11,
	0x82, 0x72, 0xc1, 0xd7, 0x14, 0x7d, 0x0a, 0x99, 0xea, 0xdb, 0x6f, 0xa3, 0xed, 0x58, 0x1a, 0xa2,
	0xa9, 0xea, 0xdb, 0xaf, 0xb6, 0xfb, 0xdf, 0x72, 0x76, 0xc7, 0x32, 0x7d, 0x09, 0x99, 0x09, 0x0d,
	0x1c, 0xcb, 0xcb, 0xed, 0x61, 0x77, 0x7d, 0x59, 0xdf, 0xee, 0x7f, 0xde, 0x17, 0x3f, 0x25, 0x54,
	0x00, 0xf9, 0xc7, 0x0e, 0x85, 0xbd, 0xb1, 0x6d, 0x55, 0x40, 0x16, 0xde, 0x28, 0xab, 0x67, 0xb0,
	0xe3, 0x28, 0x24, 0xc7, 0x9f, 0x23, 0x3a, 0x4f, 0xcf, 0x81, 0xe8, 0xf8, 0x23, 0x44, 0x57, 0xef,
	0xe0, 0x7c, 0x0e, 0xba, 0xc1, 0x68, 0x87, 0xf4, 0x05, 0x24, 0xca, 0x63, 0xef, 0x18, 0x09, 0x6a,
	0x8f, 0x16, 0xb5, 0xb8, 0x38, 0x3e, 0xc7, 0xaf, 0xff, 0x10, 0xc8, 0x23, 0xe5, 0xe8, 0x5b, 0xc8,
	0xdb, 0xf8, 0xf3, 0xf4, 0xc9, 0x52, 0xb2, 0xba, 0x86, 0xfd, 0xfd, 0x4e, 0xaf, 0x08, 0x7d, 0x03,
	0x67, 0x16, 0x85, 0x5c, 0xd7, 0xac, 0xac, 0xee, 0xaf, 0xee, 0xd2, 0xd1, 0x64, 0x0d, 0x49, 0x33,
	0x0d, 0x47, 0xe9, 0x92, 0x70, 0x9a, 0x7c, 0x2d, 0x14, 0x37, 0xf0, 0x61, 0x0f, 0xac, 0x31, 0x7d,
	0xe0, 0xb5, 0x37, 0xf5, 0x14, 0xf3, 0xe8, 0x7c, 0x2d, 0xf1, 0xfb, 0x31, 0x0d, 0x57, 0xfc, 0xfa,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x5d, 0xb6, 0xb9, 0xd7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductsClient is the client API for Products service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductsClient interface {
	Generate(ctx context.Context, in *GenerateArg, opts ...grpc.CallOption) (Products_GenerateClient, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Clear(ctx context.Context, in *ClearArg, opts ...grpc.CallOption) (*Cleared, error)
}

type productsClient struct {
	cc *grpc.ClientConn
}

func NewProductsClient(cc *grpc.ClientConn) ProductsClient {
	return &productsClient{cc}
}

func (c *productsClient) Generate(ctx context.Context, in *GenerateArg, opts ...grpc.CallOption) (Products_GenerateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Products_serviceDesc.Streams[0], "/magegrpc.Products/generate", opts...)
	if err != nil {
		return nil, err
	}
	x := &productsGenerateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Products_GenerateClient interface {
	Recv() (*Product, error)
	grpc.ClientStream
}

type productsGenerateClient struct {
	grpc.ClientStream
}

func (x *productsGenerateClient) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productsClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/magegrpc.Products/read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productsClient) Clear(ctx context.Context, in *ClearArg, opts ...grpc.CallOption) (*Cleared, error) {
	out := new(Cleared)
	err := c.cc.Invoke(ctx, "/magegrpc.Products/clear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductsServer is the server API for Products service.
type ProductsServer interface {
	Generate(*GenerateArg, Products_GenerateServer) error
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Clear(context.Context, *ClearArg) (*Cleared, error)
}

// UnimplementedProductsServer can be embedded to have forward compatible implementations.
type UnimplementedProductsServer struct {
}

func (*UnimplementedProductsServer) Generate(req *GenerateArg, srv Products_GenerateServer) error {
	return status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (*UnimplementedProductsServer) Read(ctx context.Context, req *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedProductsServer) Clear(ctx context.Context, req *ClearArg) (*Cleared, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clear not implemented")
}

func RegisterProductsServer(s *grpc.Server, srv ProductsServer) {
	s.RegisterService(&_Products_serviceDesc, srv)
}

func _Products_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateArg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductsServer).Generate(m, &productsGenerateServer{stream})
}

type Products_GenerateServer interface {
	Send(*Product) error
	grpc.ServerStream
}

type productsGenerateServer struct {
	grpc.ServerStream
}

func (x *productsGenerateServer) Send(m *Product) error {
	return x.ServerStream.SendMsg(m)
}

func _Products_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magegrpc.Products/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Products_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductsServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magegrpc.Products/Clear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductsServer).Clear(ctx, req.(*ClearArg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Products_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magegrpc.Products",
	HandlerType: (*ProductsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "read",
			Handler:    _Products_Read_Handler,
		},
		{
			MethodName: "clear",
			Handler:    _Products_Clear_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "generate",
			Handler:       _Products_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "magegrpc.proto",
}
