<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api;

use \Magento\GrpcTestApi\Api\Data\GenerateArgInterface;
use \Magento\GrpcTestApi\Api\Data\ProductInterface;
use \Magento\GrpcTestApi\Api\Data\ReadRequestInterface;
use \Magento\GrpcTestApi\Api\Data\ReadResponseInterface;
use \Magento\GrpcTestApi\Api\Data\ClearArgInterface;
use \Magento\GrpcTestApi\Api\Data\ClearedInterface;

/**
 * Autogenerated description for InMemoryProducts class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class InMemoryProducts implements ProductsInterface
{
    /**
     * @var ProductsServerInterface
     */
    private $service;

    /**
     * @param ProductsServerInterface $service
     */
    public function __construct(
        ProductsServerInterface $service
    ) {
        $this->service = $service;
    }

    /**
     * Autogenerated description for generate in memory client service method
     *
     * @param GenerateArgInterface $request
     * @return ProductInterface
     */
    public function generate(GenerateArgInterface $request): ProductInterface
    {
        return $this->service->generate($request);
    }

    /**
     * Autogenerated description for read in memory client service method
     *
     * @param ReadRequestInterface $request
     * @return ReadResponseInterface
     */
    public function read(ReadRequestInterface $request): ReadResponseInterface
    {
        return $this->service->read($request);
    }

    /**
     * Autogenerated description for clear in memory client service method
     *
     * @param ClearArgInterface $request
     * @return ClearedInterface
     */
    public function clear(ClearArgInterface $request): ClearedInterface
    {
        return $this->service->clear($request);
    }
}
