<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\GrpcTestApi\Api;

use \Magento\GrpcTestApi\Api\Data\GenerateArgInterface;
use \Magento\GrpcTestApi\Api\Data\ProductInterface;
use \Magento\GrpcTestApi\Api\Data\ReadRequestInterface;
use \Magento\GrpcTestApi\Api\Data\ReadResponseInterface;
use \Magento\GrpcTestApi\Api\Data\ClearArgInterface;
use \Magento\GrpcTestApi\Api\Data\ClearedInterface;

/**
 * Autogenerated description for ProductsServerInterface interface
 */
interface ProductsServerInterface
{
    /**
     * Autogenerated description for generate interface method
     *
     * @param GenerateArgInterface $request
     * @return ProductInterface
     * @throws \Throwable
     */
    public function generate(GenerateArgInterface $request): ProductInterface;

    /**
     * Autogenerated description for read interface method
     *
     * @param ReadRequestInterface $request
     * @return ReadResponseInterface
     * @throws \Throwable
     */
    public function read(ReadRequestInterface $request): ReadResponseInterface;

    /**
     * Autogenerated description for clear interface method
     *
     * @param ClearArgInterface $request
     * @return ClearedInterface
     * @throws \Throwable
     */
    public function clear(ClearArgInterface $request): ClearedInterface;
}
